# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/micromax/a70/extract-files.sh - DO NOT EDIT

# All the blobs necessary for A70


PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/micromax/a70/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/micromax/a70/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/micromax/a70/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/micromax/a70/proprietary/lib/libgsl.so:system/lib//libgsl.so \
    vendor/micromax/a70/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/micromax/a70/proprietary/etc/firmaware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw 

PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/micromax/a70/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/micromax/a70/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/micromax/a70/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/micromax/a70/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
    vendor/micromax/a70/proprietarylib//init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/micromax/a70/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    vendor/micromax/a70/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
    vendor/micromax/a70/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/micromax/a70/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/micromax/a70/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/micromax/a70/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/micromax/a70/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/micromax/a70/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/micromax/a70/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/micromax/a70/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/micromax/a70/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/micromax/a70/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/micromax/a70/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/micromax/a70/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/micromax/a70/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/micromax/a70/proprietary/lib/libauth.so:system/lib/libauth.so 

# Camera
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/micromax/a70/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/micromax/a70/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/micromax/a70/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/micromax/a70/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/micromax/a70/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/micromax/a70/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/micromax/a70/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/micromax/a70/proprietary/lib/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so 

# OMX
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/lib/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/micromax/a70/proprietary/lib/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/micromax/a70/proprietary/lib/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/micromax/a70/proprietary/lib/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/micromax/a70/proprietary/lib/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/micromax/a70/proprietary/lib/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/micromax/a70/proprietary/lib/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/micromax/a70/proprietary/lib/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/micromax/a70/proprietary/lib/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/micromax/a70/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/micromax/a70/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/micromax/a70/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/micromax/a70/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/micromax/a70/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/micromax/a70/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/micromax/a70/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so 

# HW
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/micromax/a70/proprietary/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/micromax/a70/proprietary/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/micromax/a70/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so 

# vendor
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/micromax/a70/proprietary/bin/vold:system/bin/vold \
    vendor/micromax/a70/proprietary/bin/modempre:system/bin/modempre \
    vendor/micromax/a70/proprietary/lib/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/micromax/a70/proprietary/lib/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/micromax/a70/proprietary/lib/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \
    vendor/micromax/a70/proprietary/lib/libmmprocess.so:system/lib/libmmprocess.so \
    vendor/micromax/a70/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/micromax/a70/proprietary/lib/libhwrpc.so:obj/lib/libhwrpc.so 

# wifi
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/bin/wl:system/bin/wl 

# bluetooth
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/micromax/a70/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/micromax/a70/proprietary/etc/bluetooth/BCM4329.hcd:system/etc/bluetooth/BCM4329.hcd 

# ril
PRODUCT_COPY_FILES += \
    vendor/micromax/a70/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/micromax/a70/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/micromax/a70/proprietary/lib/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/micromax/a70/proprietary/lib/libril.so:/system/lib/libril.so



